apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: adi253/devopsbank-app:{{ .Values.image.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: MONGODB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: DB-host

        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: DB-name

        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: DB-username

        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: DB-password

        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: APP-session
