apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  type: {{.Values.service.type}}
  ports:
  - name: {{.Values.name}}
    protocol: TCP
    port: {{.Values.port}}
    targetPort: 5000